[package]
name = "guess-the-number"
version = "0.1.0"
authors = ["Mario Cadenas"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
